name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build -t 9913/sampleapplication .
    - name: Docker run
      run: docker run 9913/sampleapplication
    - name: docker push
      run: docker push 9913/sampleapplication
